USE [master]
GO
CREATE LOGIN [BRR\JSWI] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [msdb]
GO
CREATE USER [BRR\JSWI] FOR LOGIN [BROWER\JSWI]
GO
USE [msdb]
GO
ALTER ROLE [SQLAgentUserRole] ADD MEMBER [BRR\JSWI]
GO
