USE [master]
GO
CREATE LOGIN [BROWER\JSWINDLE] FROM WINDOWS WITH DEFAULT_DATABASE=[master]
GO
USE [msdb]
GO
CREATE USER [BROWER\JSWINDLE] FOR LOGIN [BROWER\JSWINDLE]
GO
USE [msdb]
GO
ALTER ROLE [SQLAgentUserRole] ADD MEMBER [BROWER\JSWINDLE]
GO
