/*
-------------------------------------------------------------------------------------------------
        NAME: DBA_InstanceInfo.sql
  CREATED BY: Sal Young
       EMAIL: saleyoun@yahoo.com
 DESCRIPTION: 
-------------------------------------------------------------------------------------------------
CHANGE HISTORY:
DATE        MODIFIED      DESCRIPTION   
-------------------------------------------------------------------------------------------------
01.04.2017  SYoung        Initial creation.
-------------------------------------------------------------------------------------------------
  DISCLAIMER: The AUTHOR  ASSUMES NO RESPONSIBILITY  FOR ANYTHING, including  the destruction of 
              personal property, creating singularities, making deep fried chicken, causing your 
              toilet to  explode, making  your animals spin  around like mad, causing hair loss, 
              killing your buzz or ANYTHING else that can be thought up.
-------------------------------------------------------------------------------------------------
*/
:CONNECT PI
USE SQLDMRepository
GO
--[ DATABASE IS CASE SENSITIVE ]
SET NOCOUNT ON \
SELECT [SQLServerID]
      ,[InstanceName]
      ,[Active]
      --,[Deleted]
      ,[RegisteredDate]
      --,[CollectionServiceID]
      --,[UseIntegratedSecurity]
      --,[Username]
      --,[Password]
      --,[EncryptData]
      --,[TrustServerCert]
      ,[ScheduledCollectionIntervalInSeconds]
      ,[LastScheduledCollectionTime]
      ,[ServerVersion]
      ,[ServerEdition]
      ,[MaintenanceModeEnabled]
      --,[QueryMonitorEnabled]
      --,[QueryMonitorSqlBatchEventsEnabled]
      --,[QueryMonitorSqlStatementEventsEnabled]
      --,[QueryMonitorStoredProcedureEventsEnabled]
      --,[QueryMonitorDurationFilterInMilliseconds]
      --,[QueryMonitorCpuUsageFilterInMilliseconds]
      --,[QueryMonitorLogicalDiskReadsFilter]
      --,[QueryMonitorPhysicalDiskWritesFilter]
      --,[QueryMonitorTraceFileSizeKB]
      --,[QueryMonitorTraceFileRollovers]
      --,[QueryMonitorTraceRecordsPerRefresh]
      --,[ActivityMonitorEnabled]
      --,[ActivityMonitorDeadlockEventsEnabled]
      --,[ActivityMonitorAutoGrowEventsEnabled]
      --,[ActivityMonitorBlockingEventsEnabled]
      --,[ActivityMonitorBlockedProcessThreshold]
      --,[GrowthStatisticsStartTime]
      --,[ReorgStatisticsStartTime]
      --,[LastGrowthStatisticsRunTime]
      --,[LastGrowthStatisticsRunTimeUTC]
      --,[LastReorgStatisticsRunTime]
      --,[LastReorgStatisticsRunTimeUTC]
      --,[EarliestDateImportedFromLegacySQLdm]
      --,[GrowthStatisticsDays]
      --,[ReorgStatisticsDays]
      --,[TableStatisticsExcludedDatabases]
      --,[GroomAlerts]
      --,[GroomMetrics]
      --,[GroomTasks]
      --,[ReorgMinTableSizeKB]
      --,[GroomActivity]
      --,[CustomCounterTimeoutInSeconds]
      --,[OutOfProcOleAutomation]
      ,[DisableReplicationMonitoring]
      ,[MaintenanceModeType]
      ,[MaintenanceModeStart]
      ,[MaintenanceModeStop]
      ,[MaintenanceModeDays]
      --,[MaintenanceModeDurationSeconds]
      --,[MaintenanceModeRecurringStart]
      --,[QueryMonitorAdvancedConfiguration]
      --,[DisableExtendedHistoryCollection]
      --,[RefRangeUseDefaults]
      --,[RefRangeStartTimeUTC]
      --,[RefRangeEndTimeUTC]
      --,[RefRangeDays]
      --,[DisableOleAutomation]
      --,[DiskCollectionSettings]
      --,[QueryMonitorStopTimeUTC]
      --,[InputBufferLimiter]
      --,[InputBufferLimited]
      ,[ActiveClusterNode]
      ,[PreferredClusterNode]
      ,[RealServerName]
      --,[ActiveWaitCollectorStartTimeRelative]
      --,[ActiveWaitCollectorRunTimeSeconds]
      --,[ActiveWaitCollectorCollectionTimeSeconds]
      --,[ActiveWaitCollectorEnabled]
      --,[ActiveWaitLoopTimeMilliseconds]
      --,[ActiveWaitAdvancedConfiguration]
      --,[ActiveWaitXEEnable]
      --,[ActiveWaitXEFileSizeMB]
      --,[ActiveWaitXEFilesRollover]
      --,[ActiveWaitXERecordsPerRefresh]
      --,[ActiveWaitXEMaxMemoryMB]
      --,[ActiveWaitXEEventRetentionMode]
      --,[ActiveWaitXEMaxDispatchLatencySecs]
      --,[ActiveWaitXEMaxEventSizeMB]
      --,[ActiveWaitXEMemoryPartitionMode]
      --,[ActiveWaitXETrackCausality]
      --,[ActiveWaitXEStartupState]
      --,[ActiveWaitsXEFileName]
      --,[ClusterCollectionSetting]
      --,[ServerPingInterval]
      --,[VHostID]
      --,[VmUID]
      --,[VmName]
      --,[VmDomainName]
      --,[AlertRefreshInMinutes]
      --,[DatabaseStatisticsRefreshIntervalInSeconds]
      --,[WmiCollectionEnabled]
      --,[WmiConnectAsService]
      --,[WmiUserName]
      --,[WmiPassword]
      --,[LastDatabaseCollectionTime]
      --,[LastAlertRefreshTime]
      --,[GroomAudit]
      --,[MaintenanceModeMonth]
      --,[MaintenanceModeSpecificDay]
      --,[MaintenanceModeWeekOrdinal]
      --,[MaintenanceModeWeekDay]
      --,[MaintenanceModeMonthDuration]
      --,[MaintenanceModeMonthRecurringStart]
      --,[QueryMonitorTraceMonitoringEnabled]
      --,[QueryMonitorCollectQueryPlan]
      --,[ActivityMonitorTraceMonitoringEnabled]
      --,[ActivityMonitorXEFileSizeMB]
      --,[ActivityMonitorXEFilesRollover]
      --,[ActivityMonitorXERecordsPerRefresh]
      --,[ActivityMonitorXEMaxMemoryMB]
      --,[ActivityMonitorXEEventRetentionMode]
      --,[ActivityMonitorXEMaxDispatchLatencySecs]
      --,[ActivityMonitorXEMaxEventSizeMB]
      --,[ActivityMonitorXEMemoryPartitionMode]
      --,[ActivityMonitorXETrackCausality]
      --,[ActivityMonitorXEStartupState]
      --,[ActivityMonitorXEFileName]
      --,[QueryMonitorXEFileSizeMB]
      --,[QueryMonitorXEFilesRollover]
      --,[QueryMonitorCollectEstimatedQueryPlan]
      --,[CloudProviderId]
      --,[GroomPrescriptiveAnalysis]
      --,[FriendlyServerName]
      --,[InstanceScaleFactor]
      --,[IsUserSysAdmin]
  FROM [SQLdmRepository].[dbo].[MonitoredSQLServers]
 WHERE 1 = 1
   AND Active = 1